2021-06-30 23:50:53,674 INFO    MainThread:17980 [wandb_setup.py:_flush():69] setting env: {}
2021-06-30 23:50:53,674 INFO    MainThread:17980 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-30 23:50:53,674 INFO    MainThread:17980 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-30 23:50:53,675 INFO    MainThread:17980 [wandb_init.py:_log_setup():337] Logging user logs to C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_235053-psngmuue\logs\debug.log
2021-06-30 23:50:53,675 INFO    MainThread:17980 [wandb_init.py:_log_setup():338] Logging internal logs to C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_235053-psngmuue\logs\debug-internal.log
2021-06-30 23:50:53,676 INFO    MainThread:17980 [wandb_init.py:_jupyter_setup():288] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000026F1572D198>
2021-06-30 23:50:53,678 INFO    MainThread:17980 [wandb_init.py:init():370] calling init triggers
2021-06-30 23:50:53,678 INFO    MainThread:17980 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-06-30 23:50:53,678 INFO    MainThread:17980 [wandb_init.py:init():419] starting backend
2021-06-30 23:50:53,678 INFO    MainThread:17980 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=spawn, using: spawn
2021-06-30 23:50:53,686 INFO    MainThread:17980 [backend.py:ensure_launched():135] starting backend process...
2021-06-30 23:50:53,997 INFO    MainThread:17980 [backend.py:ensure_launched():140] started backend process with pid: 19184
2021-06-30 23:50:53,998 INFO    MainThread:17980 [wandb_init.py:init():424] backend started and connected
2021-06-30 23:50:54,444 INFO    MainThread:17980 [wandb_run.py:_label_probe_notebook():845] probe notebook
2021-06-30 23:50:54,447 INFO    MainThread:17980 [wandb_run.py:_label_probe_notebook():852] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-06-30 23:50:54,447 INFO    MainThread:17980 [wandb_init.py:init():472] updated telemetry
2021-06-30 23:50:54,449 INFO    MainThread:17980 [wandb_init.py:init():491] communicating current version
2021-06-30 23:50:57,176 INFO    MainThread:17980 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.10.33 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-06-30 23:50:57,178 INFO    MainThread:17980 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-06-30 23:50:57,696 INFO    MainThread:17980 [wandb_init.py:init():529] starting run threads in backend
2021-06-30 23:50:58,609 INFO    MainThread:17980 [wandb_run.py:_console_start():1624] atexit reg
2021-06-30 23:50:58,611 INFO    MainThread:17980 [wandb_run.py:_redirect():1498] redirect: SettingsConsole.WRAP
2021-06-30 23:50:58,612 INFO    MainThread:17980 [wandb_run.py:_redirect():1535] Wrapping output streams.
2021-06-30 23:50:58,615 INFO    MainThread:17980 [wandb_run.py:_redirect():1559] Redirects installed.
2021-06-30 23:50:58,615 INFO    MainThread:17980 [wandb_init.py:init():554] run started, returning control to user process
2021-06-30 23:51:11,651 INFO    MainThread:17980 [wandb_init.py:_pause_backend():250] pausing backend
2021-06-30 23:51:11,651 INFO    MainThread:17980 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-07-01 01:53:14,132 INFO    MainThread:17980 [wandb_run.py:_atexit_cleanup():1594] got exitcode: 0
2021-07-01 01:53:14,132 INFO    MainThread:17980 [wandb_run.py:_restore():1566] restore
2021-07-01 01:53:14,503 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 994
  total_bytes: 994
}

2021-07-01 01:53:14,822 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 994
  total_bytes: 994
}

2021-07-01 01:53:15,417 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 994
  total_bytes: 4947
}

2021-07-01 01:53:15,819 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 994
  total_bytes: 4949
}

2021-07-01 01:53:15,974 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3251
  total_bytes: 4949
}

2021-07-01 01:53:16,077 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4949
  total_bytes: 4949
}

2021-07-01 01:53:16,180 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4949
  total_bytes: 4949
}

2021-07-01 01:53:16,282 INFO    MainThread:17980 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4949
  total_bytes: 4949
}

