2021-06-30 20:03:25,207 INFO    MainThread:14312 [wandb_setup.py:_flush():69] setting env: {}
2021-06-30 20:03:25,208 INFO    MainThread:14312 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-30 20:03:25,208 INFO    MainThread:14312 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-30 20:03:25,208 INFO    MainThread:14312 [wandb_init.py:_log_setup():337] Logging user logs to C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_200325-39au2ip2\logs\debug.log
2021-06-30 20:03:25,208 INFO    MainThread:14312 [wandb_init.py:_log_setup():338] Logging internal logs to C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_200325-39au2ip2\logs\debug-internal.log
2021-06-30 20:03:25,224 INFO    MainThread:14312 [wandb_init.py:_jupyter_setup():288] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001DB1EC34240>
2021-06-30 20:03:25,224 INFO    MainThread:14312 [wandb_init.py:init():370] calling init triggers
2021-06-30 20:03:25,224 INFO    MainThread:14312 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-06-30 20:03:25,224 INFO    MainThread:14312 [wandb_init.py:init():419] starting backend
2021-06-30 20:03:25,225 INFO    MainThread:14312 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=spawn, using: spawn
2021-06-30 20:03:25,230 INFO    MainThread:14312 [backend.py:ensure_launched():135] starting backend process...
2021-06-30 20:03:25,379 INFO    MainThread:14312 [backend.py:ensure_launched():140] started backend process with pid: 13456
2021-06-30 20:03:25,380 INFO    MainThread:14312 [wandb_init.py:init():424] backend started and connected
2021-06-30 20:03:25,401 INFO    MainThread:14312 [wandb_run.py:_label_probe_notebook():845] probe notebook
2021-06-30 20:03:25,402 INFO    MainThread:14312 [wandb_run.py:_label_probe_notebook():852] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-06-30 20:03:25,402 INFO    MainThread:14312 [wandb_init.py:init():472] updated telemetry
2021-06-30 20:03:25,404 INFO    MainThread:14312 [wandb_init.py:init():491] communicating current version
2021-06-30 20:03:27,988 INFO    MainThread:14312 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.10.33 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-06-30 20:03:27,988 INFO    MainThread:14312 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-06-30 20:03:28,426 INFO    MainThread:14312 [wandb_init.py:init():529] starting run threads in backend
2021-06-30 20:03:29,169 INFO    MainThread:14312 [wandb_run.py:_console_start():1624] atexit reg
2021-06-30 20:03:29,170 INFO    MainThread:14312 [wandb_run.py:_redirect():1498] redirect: SettingsConsole.WRAP
2021-06-30 20:03:29,170 INFO    MainThread:14312 [wandb_run.py:_redirect():1535] Wrapping output streams.
2021-06-30 20:03:29,173 INFO    MainThread:14312 [wandb_run.py:_redirect():1559] Redirects installed.
2021-06-30 20:03:29,173 INFO    MainThread:14312 [wandb_init.py:init():554] run started, returning control to user process
2021-06-30 20:03:36,976 INFO    MainThread:14312 [wandb_init.py:_pause_backend():250] pausing backend
2021-06-30 20:03:36,976 INFO    MainThread:14312 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-06-30 20:08:17,421 INFO    MainThread:14312 [wandb_init.py:_resume_backend():259] resuming backend
2021-06-30 20:08:17,480 INFO    MainThread:14312 [wandb_init.py:_pause_backend():250] pausing backend
2021-06-30 20:08:17,480 INFO    MainThread:14312 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-06-30 20:08:43,121 INFO    MainThread:14312 [wandb_init.py:_resume_backend():259] resuming backend
2021-06-30 20:08:43,182 INFO    MainThread:14312 [wandb_init.py:_pause_backend():250] pausing backend
2021-06-30 20:08:43,182 INFO    MainThread:14312 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-06-30 20:08:50,459 INFO    MainThread:14312 [wandb_init.py:_resume_backend():259] resuming backend
2021-06-30 20:08:50,584 INFO    MainThread:14312 [wandb_setup.py:_flush():69] setting env: {}
2021-06-30 20:08:50,584 INFO    MainThread:14312 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-30 20:08:50,584 INFO    MainThread:14312 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-30 20:08:50,584 INFO    MainThread:14312 [wandb_init.py:_log_setup():337] Logging user logs to C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_200850-2q2f118x\logs\debug.log
2021-06-30 20:08:50,584 INFO    MainThread:14312 [wandb_init.py:_log_setup():338] Logging internal logs to C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_200850-2q2f118x\logs\debug-internal.log
2021-06-30 20:08:50,599 INFO    MainThread:14312 [wandb_init.py:init():370] calling init triggers
2021-06-30 20:08:50,599 INFO    MainThread:14312 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-06-30 20:08:50,599 INFO    MainThread:14312 [wandb_init.py:init():392] re-initializing run, found existing run on stack: 39au2ip2
2021-06-30 20:08:50,599 INFO    MainThread:14312 [wandb_run.py:finish():1294] finishing run abhishekdiphu/visualize-sklearn/39au2ip2
